name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      azure_cred: ${{ secrets.AZURE_CREDENTIALS }}  
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      - name: secretBash	
        run: |
          $azure_cred = $env:azure_cred
          echo $azure_cred
          sed -i -e 's/TESTSERVICENAME/'$azure_cred'/g' .cloud/.azure/test/test_deploy.json
          
# Connect or Create the Azure Machine Learning Workspace
#     - name: deploy all resources
#       id: aml_configure
#       uses: ashishonce/aml_configure@master
#       with:
#           azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
#           armtemplate_file: "deploy.json"
#           armtemplateparams_file: "deploy.params.json"
#           resource_group: "ashkuma_functionAppRsGroup"
