name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      pathname: ${{ github.event.payload.ref }}  
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      - name: secretBash	
        run: |
          echo  $env:pathname
# Connect or Create the Azure Machine Learning Workspace
#     - name: deploy all resources
#       id: aml_configure
#       uses: ashishonce/aml_configure@master
#       with:
#           azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
#           armtemplate_file: "deploy.json"
#           armtemplateparams_file: "deploy.params.json"
#           resource_group: "ashkuma_functionAppRsGroup"
